---
- name: Install WordPress, MySQL, Nginx, and PHP
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
          - common
          - mysql
          - nginx
          - php
          - wordpress
