---
- name: Update repositories cache
  apt: update_cache=yes

- name: Install build-essential
  apt: name=build-essential state=present

- name: Install the libselinux-python package
  apt: name=python-selinux state=present

- name: Reload ansible_facts
  setup:

- name: Install iptables service
  apt: name=iptables state=present

- name: Set up iptables rules
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    protocol: tcp
    destination_port: 8080
  become: yes
